services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    user: "0:0"

    # Load clean, version-controlled environment variables
    env_file:
      - .env

    # Persist workflows, credentials, execution data
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./backups:/backups
    # Attach to the existing reverse-proxy network
    networks:
      - nginx_network

    # Health-check for easier monitoring
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5

# ────────────────────────────────────────────────
# Named volumes
# ────────────────────────────────────────────────
volumes:
  n8n_data:

# ────────────────────────────────────────────────
# External networks
# ────────────────────────────────────────────────
networks:
  nginx_network:
    external: true

